version: '3'
services:
  dependencies:
    build:
      context: .
      dockerfile: Dockerfile
    image: base
  todo-service:
    build:
      context: ./todo_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/tasks:/data/tasks
      - ./logs:/app/logs
      - ./db/tasks_init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - dependencies
  url-shortener:
    build:
      context: ./url_shortener
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./data/urls:/data/urls
      - ./logs:/app/logs
      - ./db/urls_init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - dependencies
